name: '[test-python-gitlab]'

on: [ 'push' ]
jobs:
  check-importable:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7' ]
        python-gitlab-version: [ '2.7.1', '2.6.0' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python-gitlab ${{ matrix.python-gitlab-version }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install python-gitlab==${{ matrix.python-gitlab-version }}
    
    - name: run main
      run: |
        python example.py